version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=server
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
  
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=server
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: >
      sh -c "postgres -D /var/lib/postgresql/data"