version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"